apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nest1419/rke2.git
    targetRevision: main
    path: app2/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
